#ifndef SOUNDLV2LIB_GLOBAL_H
#define SOUNDLV2LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOUNDLV2LIB_LIBRARY)
#  define SOUNDLV2LIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SOUNDLV2LIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SOUNDLV2LIB_GLOBAL_H
